services:
  frontend:
    build: overheard-frontend
    image: overheard-frontend
    restart: "no"
    volumes:
      - ./overheard-frontend/:/frontend
      - /frontend/node_modules
    ports:
      - 5173:5173
    depends_on:
      - backend

  backend:
    build: overheard-backend
    image: overheard-backend
    restart: "no"
    volumes:
      - ./overheard-backend/:/backend
      - /backend/node_modules
    ports:
      - 3003:3003
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/Overheard"  

  mongodb:
    image: mongo:latest
    container_name: overheard-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    