services:
  offgrid:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app
    expose:
      - 1234
    volumes:
      - ./app/:/app
      - /app/node_modules
    depends_on:
      - db
      - flyway
    env_file:
      - project.env

  db:
    container_name: db-server
    image: postgres:latest
    restart: "no"
    env_file:
      - project.env
    expose:
      - 5432  

  flyway:
    image: flyway/flyway:latest-alpine
    depends_on:
      - db
    volumes:
      - .:/flyway/sql
    command: -connectRetries=30 -baselineOnMigrate=true migrate
    env_file:
      - project.env